//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothingShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<employee_type> employee_type { get; set; }
        public virtual DbSet<expense> expense { get; set; }
        public virtual DbSet<inventory> inventory { get; set; }
        public virtual DbSet<marchandise_supplier_order> marchandise_supplier_order { get; set; }
        public virtual DbSet<merchandise> merchandise { get; set; }
        public virtual DbSet<merchandise_category> merchandise_category { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<shift> shift { get; set; }
        public virtual DbSet<supplier_order> supplier_order { get; set; }
    }
}
