//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothingShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supplier_order()
        {
            this.marchandise_supplier_order = new HashSet<marchandise_supplier_order>();
        }
    
        public int Id { get; set; }
        public System.DateTime arrival_time { get; set; }
        public bool arrived { get; set; }
        public bool deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<marchandise_supplier_order> marchandise_supplier_order { get; set; }
    }
}
